# Common NixOS configuration shared across all hosts
{ config, pkgs, lib, inputs, hostname, ... }:

let
  pywalfoxNativeMessagingHost = pkgs.writeTextDir "lib/mozilla/native-messaging-hosts/pywalfox.json" (
    builtins.toJSON {
      name = "pywalfox";
      description = "Automatically theme your browser using the colors generated by Pywal";
      path = lib.getExe pkgs.pywalfox-native;
      type = "stdio";
      allowed_extensions = [ "pywalfox@frewacom.org" ];
    }
  );
in
{
  imports = [
    ./firewall.nix
    ./logiops.nix
    ./programs.nix
  ];

  # Set hostname from flake
  networking.hostName = hostname;

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # Enable networking. NordVPN manual profiles use OpenVPN through
  # NetworkManager, which also makes them visible to Noctalia's VPN widget.
  networking.networkmanager = {
    enable = true;
    plugins = with pkgs; [
      networkmanager-openvpn
    ];
  };

  # Firmware updates via LVFS (includes UEFI/BIOS when supported)
  services.fwupd.enable = true;

  # Set your time zone
  time.timeZone = "Europe/Zurich";

  # Internationalisation
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "de_CH.UTF-8";
    LC_IDENTIFICATION = "de_CH.UTF-8";
    LC_MEASUREMENT = "de_CH.UTF-8";
    LC_MONETARY = "de_CH.UTF-8";
    LC_NAME = "de_CH.UTF-8";
    LC_NUMERIC = "de_CH.UTF-8";
    LC_PAPER = "de_CH.UTF-8";
    LC_TELEPHONE = "de_CH.UTF-8";
    LC_TIME = "de_CH.UTF-8";
  };

  # Keep xserver enabled for shared XKB/libinput plumbing while the desktop
  # session itself is Wayland-only.
  services.xserver.enable = true;

  # greetd starts Niri directly for krieger, then falls back to a text greeter
  # if that session exits or fails before Noctalia can lock it.
  services.displayManager.gdm.enable = false;
  services.greetd = {
    enable = true;
    restart = false;
    useTextGreeter = true;
    settings = {
      initial_session = {
        command = "${config.programs.niri.package}/bin/niri-session";
        user = "krieger";
      };
      default_session = {
        command = "${pkgs.greetd}/bin/agreety --cmd ${config.programs.niri.package}/bin/niri-session";
        user = "greeter";
      };
    };
  };

  # Enable Niri compositor (niri-flake module handles session registration)
  programs.niri.enable = true;
  # niri-flake also starts a KDE polkit agent by default; disable it because
  # Noctalia provides the polkit agent and multiple agents conflict.
  systemd.user.services.niri-flake-polkit.enable = false;

  # XDG Desktop Portal for Niri (file dialogs, screen sharing)
  xdg.portal = {
    enable = true;
    extraPortals = with pkgs; [
      xdg-desktop-portal-gtk
      xdg-desktop-portal-gnome  # For ScreenCast/RemoteDesktop support
    ];
    # Override Niri's default portal ordering so apps that need file pickers
    # (e.g. Steam chat image upload) use GTK first.
    config.niri = {
      default = [ "gtk" "gnome" ];
      "org.freedesktop.impl.portal.FileChooser" = [ "gtk" ];
      # Keep GNOME backend for interfaces GTK does not implement.
      "org.freedesktop.impl.portal.ScreenCast" = [ "gnome" ];
      "org.freedesktop.impl.portal.Screenshot" = [ "gnome" ];
      "org.freedesktop.impl.portal.RemoteDesktop" = [ "gnome" ];
      "org.freedesktop.impl.portal.Secret" = [ "gnome-keyring" ];
    };
  };

  # Flatpak (Discord is installed from Flathub; see activation script below).
  services.flatpak.enable = true;

  # Flathub + Discord: idempotent on every switch; skips cleanly if Flathub is
  # unreachable during activation.
  system.activationScripts.flatpak-flathub-discord = {
    text = ''
      flatpak=${pkgs.flatpak}/bin/flatpak

      if ! "$flatpak" remotes --system --columns=name | ${pkgs.gnugrep}/bin/grep -qx flathub; then
        if ! "$flatpak" remote-add --system --if-not-exists flathub \
          https://flathub.org/repo/flathub.flatpakrepo; then
          echo "warning: Flathub is unreachable; skipping Discord Flatpak setup" >&2
          exit 0
        fi
      fi

      if ! "$flatpak" info --system com.discordapp.Discord >/dev/null 2>&1; then
        if ! "$flatpak" install --system --noninteractive -y \
          flathub com.discordapp.Discord; then
          echo "warning: Discord Flatpak install failed; continuing activation" >&2
        fi
      fi
    '';
  };

  # Power management (can be overridden by hosts using TLP)
  services.power-profiles-daemon.enable = lib.mkDefault true;

  # GNOME Keyring for credential storage (used by apps like VS Code, browsers)
  services.gnome.gnome-keyring.enable = true;
  security.pam.services.greetd.enableGnomeKeyring = true;
  security.pam.services.noctalia-lock.enableGnomeKeyring = true;

  # GVFS — backs Nautilus's trash bin (`trash:///`), the remote shares
  # under "Other Locations" (sftp, smb, ftp, mtp, ...), MTP-mounted
  # phones in any GTK file picker, and the GVFS mounts that show up in
  # EOG / Firefox "Save to" dialogs.
  services.gvfs.enable = true;

  # GNOME Boxes (and virt-manager on hp-nix) use libvirt/QEMU.
  virtualisation.libvirtd.enable = true;

  # Configure keymap
  services.xserver.xkb = {
    layout = "ch";
    variant = "";
  };
  console.keyMap = "sg";

  # Enable CUPS printing
  services.printing.enable = true;

  # Enable sound with PipeWire
  services.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # User account
  users.users.krieger = {
    isNormalUser = true;
    description = "Krieger";
    extraGroups = [ "networkmanager" "wheel" "video" "audio" "input" "kvm" "libvirtd" ];
    packages = with pkgs; [];
  };

  # Firefox
  programs.firefox = {
    enable = true;
    nativeMessagingHosts.packages = [
      pywalfoxNativeMessagingHost
    ];
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # Enable flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # Nix path
  nix.nixPath = [ "nixpkgs=/etc/channels/nixpkgs" ];

  # Automatic garbage collection (30 days retention)
  nix.gc = {
    automatic = true;
    dates = "weekly";
    options = "--delete-older-than 30d";
  };

  # Optimize nix store
  nix.settings.auto-optimise-store = true;

  # Enable SSH daemon
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "no";
      PasswordAuthentication = true;  # Set to false after setting up SSH keys
    };
  };

  # Automatic system updates
  system.autoUpgrade = {
    enable = true;
    flake = "/home/krieger/CirnOS#${hostname}";
    dates = "weekly";
    allowReboot = false;  # Set to true if you want automatic reboots
  };

  # System state version
  system.stateVersion = "24.11";
}
